spring:
  datasource:
    url: jdbc:mysql://localhost/isteklifsistemi?useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level: debug
